[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 1000000

remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "solady/=lib/gas-station/lib/solady/src/"
]

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }

[rpc_endpoints]
base = "https://mainnet.base.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options